### ISSUE TITLE
exception handling in Job.send()

### ISSUE THREAD

**Issue by nickburlett** [allink/pennyblack#48]
in `Job.send`, if `connection.send_messages` raises an exception, the Job status is set to 41 (error) but not saved, so the Job status stays pending. 

Additionally, the `smtplib.SMTPRecipientsRefused` exception can be raised from `send_messages`, indicating that one of the messages could not be sent. This doesn't mean that the entire job is in error, just one of the recipients, but `Job.send` will abort the remainder of the sending anyway. I encountered this when there was a typo in the domain of a recipient's email address.

**Comment by WarToaster** [comment]
Hi Nick

pennyblack is no longer being maintained as we ourselves have switched to a new provider.
Please consider forking the project and fixing the issue yourself.

Cheers

**Comment by nickburlett** [comment]
@WarToaster , I've actually fixed it my local checkout, and I was going to issue a pull request once I've done some more testing. I may still issue the pull request just so it's seen by others who might still be using pennyblack.

**Comment by nickburlett** [comment]
My fork has differed enough that the pull request is large. Anyone wanting the fix for this can grab https://github.com/nickburlett/pennyblack/commit/301d0328524ff70ed269f9dd6efde9931b518b3e
